[package]
name = "pinetime-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
nrf52832-hal = "0.14.1"
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
