[default.probe]
protocol = "Swd"

[default.flashing]
enabled = true
restore_unwritten_bytes = false

[default.reset]
enabled = true

[default.general]
chip = "nrf52832_xxAA"

[default.rtt]
enabled = true
